declare function messageType(): number;
declare function body(): Uint8Array;
declare function now(): number;
declare function steamId(): bigint;
declare function accountId(): number;
declare function personaName(): string;
declare function decode<TMessage = unknown>(typeName: string, payload: Uint8Array): TMessage;
declare function encode<TMessage = unknown>(typeName: string, value: TMessage): Uint8Array;
declare function send(messageType: number, payload: Uint8Array | number[], protobuf?: boolean): boolean;
declare function reply(messageType: number, payload: Uint8Array | number[], protobuf?: boolean): boolean;
declare function log(message: string): void;

declare function deadlockRecordClientVersion(accountId: number, version: number): number;
declare function deadlockClientVersion(accountId?: number): number;
declare function deadlockAccountStats(...args: any[]): any;
declare function deadlockAllocateEphemeralMatchId(...args: any[]): any;
declare function deadlockAllocateEphemeralMatchLobbyId(...args: any[]): any;
declare function deadlockCurrentLeaveLobbyId(...args: any[]): any;
declare function deadlockDedicatedServerState(...args: any[]): any;
declare function deadlockEnsurePlayer(...args: any[]): any;
declare function deadlockHeroStats(...args: any[]): any;
declare function deadlockInspectCurrentMatchSignoutV2(...args: any[]): any;
declare function deadlockIsDedicatedGameServer(...args: any[]): any;
declare function deadlockMatchHistory(...args: any[]): any;
declare function deadlockQueueGcMessageForAccount(...args: any[]): any;
declare function deadlockRankedSocache(...args: any[]): any;
declare function deadlockReleaseDedicatedServer(...args: any[]): any;
declare function deadlockResolveClientConnectIp(...args: any[]): any;
declare function deadlockScheduleCurrentMatchSignoutRelease(...args: any[]): any;
declare function deadlockStartDedicatedServer(...args: any[]): any;
declare function deadlockUpdateCurrentLobbyServerState(...args: any[]): any;
